FROM registry.access.redhat.com/ubi9/ubi:latest as builder

WORKDIR /app
USER root
RUN dnf install -y wget tar git make && \
    wget https://go.dev/dl/go1.24.1.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz && \
    rm -f go1.24.1.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}"
RUN git clone https://github.com/manusa/kubernetes-mcp-server.git && \
    cd kubernetes-mcp-server && \
    make build

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
WORKDIR /app
COPY --from=builder /app/kubernetes-mcp-server/kubernetes-mcp-server /app/kubernetes-mcp-server
ENTRYPOINT ["./kubernetes-mcp-server", "--sse-port", "8080", "--log-level", "9"]

EXPOSE 8080
