FROM registry.access.redhat.com/ubi9/python-311:latest

WORKDIR /llamastack

COPY requirements.txt /llamastack/
RUN pip install -r requirements.txt

RUN pip install mcp["cli"]

COPY . /llamastack

EXPOSE 8000

ENTRYPOINT ["python", "mcp_server.py", "./openapi.json", "--port", "8000", "--transport", "sse"]
