#!/bin/bash
# Configure Workshop Template System workflows

echo "🎯 Workshop Template System Workflow Configuration"
echo "=================================================="

echo ""
echo "📋 Workflow 1: Repository-Based Workshop Creation"
echo "Source: https://github.com/tosin2013/healthcare-ml-genetic-predictor.git"
echo "Foundation: https://github.com/rhpds/showroom_template_default.git"
echo "Process: Application → Analysis → Showroom Template → Workshop"
echo ""
echo "Example command to start Workflow 1:"
echo "curl -X POST https://${TEMPLATE_CONVERTER_URL}/send-task \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"id\": \"healthcare-ml-analysis\","
echo "    \"params\": {"
echo "      \"sessionId\": \"workflow-1-session\","
echo "      \"message\": {"
echo "        \"role\": \"user\","
echo "        \"parts\": [{"
echo "          \"type\": \"text\","
echo "          \"text\": \"Analyze https://github.com/tosin2013/healthcare-ml-genetic-predictor.git for workshop conversion using Showroom template\""
echo "        }]"
echo "      }"
echo "    }"
echo "  }'"

echo ""
echo "🔧 Workflow 3: Workshop Enhancement"
echo "Source: Gitea repository (imported from Red Hat SE RTO)"
echo "Process: Existing Workshop → Analysis → Enhancement → Modernization"
echo ""
echo "Example command to start Workflow 3:"
echo "curl -X POST https://${TEMPLATE_CONVERTER_URL}/send-task \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"id\": \"openshift-baremetal-enhancement\","
echo "    \"params\": {"
echo "      \"sessionId\": \"workflow-3-session\","
echo "      \"message\": {"
echo "        \"role\": \"user\","
echo "        \"parts\": [{"
echo "          \"type\": \"text\","
echo "          \"text\": \"Enhance the OpenShift Bare Metal workshop from Gitea repository with modern practices\""
echo "        }]"
echo "      }"
echo "    }"
echo "  }'"

echo ""
echo "🚀 Next Steps:"
echo "1. Test agent connectivity with /agent-card endpoints"
echo "2. Start Workflow 1 for healthcare-ml-genetic-predictor"
echo "3. Start Workflow 3 for openshift-baremetal-workshop"
echo "4. Monitor agent progress and generated content"
echo "5. Verify BuildConfig triggers and workshop deployments"
