kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio-tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-tempo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-tempo
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-tempo
      containers:
        - resources: {}
          name: minio-tempo
          command:
            - /bin/sh
            - '-c'
            - |
              mkdir -p /storage/tempo && \
              minio server /storage
          env:
            # TEST VALUES ONLY USED IN TEST DEV ENV
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-user-creds
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-user-creds
                  key: MINIO_ROOT_PASSWORD
          ports:
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: storage
              mountPath: /storage
          image: quay.io/minio/minio
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext: {}
  strategy:
    type: Recreate
  progressDeadlineSeconds: 600
