apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    notebooks.opendatahub.io/last-size-selection: Small
    notebooks.opendatahub.io/last-image-selection: quay.io/redhat-et/lab:6-10-2025
    opendatahub.io/accelerator-name: ""
    opendatahub.io/hardware-profile-name: ""
    opendatahub.io/image-display-name: Custom ET image
    openshift.io/description: ""
    openshift.io/display-name: lab
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app: lab
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
  name: lab
spec:
  template:
    spec:
      initContainers:
      - name: repo-clone
        image: alpine/git:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Cloning repository..."
          git clone https://github.com/rhpds/llama-stack-on-ocp.git /tmp/repo

          echo "Copying notebooks to persistent storage..."
          mkdir -p /workspace/
          cp -r /tmp/repo/demos/rag_agentic/notebooks/* /workspace/
          cp -r /tmp/repo/demos/rag_agentic/lab-container/requirements.txt /workspace/
          mkdir /workspace/src
          mkdir /workspace/images
          cp -r /tmp/repo/demos/rag_agentic/src/utils.py /workspace/src/
          cp -r /tmp/repo/demos/rag_agentic/src/client_tools.py /workspace/src/
          cp -r /tmp/repo/.env.example /workspace/.env
          echo "Notebook files copied successfully!"
        volumeMounts:
        - name: lab-storage
          mountPath: /workspace
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
                              --ServerApp.token=''
                              --ServerApp.password=''
                              --ServerApp.base_url=/notebook/llama-serve/lab
                              --ServerApp.quit_button=False
        - name: JUPYTER_IMAGE
          value: s2i-generic-data-science-notebook:2025.1
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIP_CERT
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: SSL_CERT_FILE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: JUPYTER_CONFIG_DATA
          value: '{"FileContentsManager": {"list_hidden": true}}'
        image: quay.io/redhat-et/lab:6-10-2025
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/llama-serve/lab/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: lab
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/llama-serve/lab/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 8Gi
        volumeMounts:
        - mountPath: /opt/app-root/src/
          name: lab-storage
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
        workingDir: /opt/app-root/src
      - args:
        - --provider=openshift
        - --https-address=:8443
        - --http-address=
        - --openshift-service-account=lab
        - --cookie-secret-file=/etc/oauth/config/cookie_secret
        - --cookie-expire=24h0m0s
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --upstream=http://localhost:8888
        - --upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --email-domain=*
        - --skip-provider-button
        - --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"lab","namespace":"$(NAMESPACE)"}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4f8d66597feeb32bb18699326029f9a71a5aca4a57679d636b876377c2e95695
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: oauth-proxy
        ports:
        - containerPort: 8443
          name: oauth-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/oauth/config
          name: oauth-config
        - mountPath: /etc/tls/private
          name: tls-certificates
      enableServiceLinks: false
      serviceAccountName: lab
      volumes:
      - name: lab-storage
        persistentVolumeClaim:
          claimName: lab-storage
      - emptyDir:
          medium: Memory
        name: shm
      - configMap:
          items:
          - key: ca-bundle.crt
            path: ca-bundle.crt
          name: workbench-trusted-ca-bundle
          optional: true
        name: trusted-ca
      - name: oauth-config
        secret:
          defaultMode: 420
          secretName: lab-oauth-config
      - name: tls-certificates
        secret:
          defaultMode: 420
          secretName: lab-tls
