apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-chat-agent
  namespace: workshop-system
  labels:
    app: workshop-chat-agent
    component: workshop-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workshop-chat-agent
  template:
    metadata:
      labels:
        app: workshop-chat-agent
        component: workshop-agent
    spec:
      serviceAccountName: workshop-system-sa
      containers:
      - name: workshop-chat-agent
        image: workshop-system:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: AGENT_NAME
          value: "workshop_chat"
        - name: AGENT_PORT
          value: "8080"
        - name: LLAMA_STACK_ENDPOINT
          value: "http://llama-stack-server:8321"
        - name: INFERENCE_MODEL_ID
          value: "meta-llama/Llama-3.2-3B-Instruct"
        - name: MILVUS_ENDPOINT
          value: "http://milvus:19530"
        - name: RAG_ENABLED
          value: "true"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /agent-card
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /agent-card
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
