apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: healthcare-ml-workshop
  namespace: workshop-system
  labels:
    app: healthcare-ml-workshop
spec:
  lookupPolicy:
    local: false

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openshift-baremetal-workshop
  namespace: workshop-system
  labels:
    app: openshift-baremetal-workshop
spec:
  lookupPolicy:
    local: false

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: workshop-system
  namespace: workshop-system
  labels:
    app: workshop-template-system
spec:
  lookupPolicy:
    local: false
