apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-system-sa
  namespace: workshop-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workshop-system-role
  namespace: workshop-system
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["build.openshift.io"]
  resources: ["buildconfigs", "builds"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["image.openshift.io"]
  resources: ["imagestreams"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workshop-system-rolebinding
  namespace: workshop-system
subjects:
- kind: ServiceAccount
  name: workshop-system-sa
  namespace: workshop-system
roleRef:
  kind: Role
  name: workshop-system-role
  apiGroup: rbac.authorization.k8s.io
