apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-monitoring-service
spec:
  template:
    spec:
      containers:
      - name: workshop-monitoring-service
        env:
        - name: QUARKUS_LOG_LEVEL
          value: "INFO"
        - name: WORKSHOP_HEALTH_CHECK_INTERVAL
          value: "30s"
        - name: GITEA_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitea-credentials
              key: GITEA_TOKEN
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8086
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
