apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: workshop-monitoring-service-production

namespace: workshop-system

resources:
- ../../base

labels:
- pairs:
    environment: production

patches:
- path: deployment-patch.yaml

replicas:
- name: workshop-monitoring-service
  count: 2

images:
- name: workshop-monitoring-service
  newTag: v1.0.0
