FROM registry.access.redhat.com/ubi9/nodejs-22:latest AS builder

USER root
RUN dnf install -y git && dnf clean all

WORKDIR /app
RUN git clone https://github.com/modelcontextprotocol/servers.git .

WORKDIR /app/src/github

RUN npm install
RUN npm run build

FROM registry.access.redhat.com/ubi9/nodejs-22:latest AS release

WORKDIR /opt/app-root/src

COPY --from=builder /app/src/github/dist ./dist
COPY --from=builder /app/src/github/package.json ./package.json

ENV NODE_ENV=production

RUN npm install --omit=dev --no-package-lock --ignore-scripts

ENTRYPOINT ["node", "dist/index.js"]

EXPOSE 8080
