FROM node:22.12-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app
RUN git clone https://github.com/modelcontextprotocol/servers.git .

WORKDIR /app/src/github

RUN npm install
RUN npm run build

FROM node:22.12-alpine AS release

WORKDIR /app

COPY --from=builder /app/src/github/dist /app/dist
COPY --from=builder /app/src/github/package.json /app/package.json

ENV NODE_ENV=production

RUN npm install --omit=dev --no-package-lock --ignore-scripts

ENTRYPOINT ["node", "dist/index.js"]

EXPOSE 8080
