# OpenShift Pipelines Operator Subscription
# Note: This subscription already exists in the cluster
# Current status: openshift-pipelines-operator-rh.v1.18.1 is installed and running
# This file is for reference only - the operator is already deployed

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
  labels:
    app: workshop-template-system
    component: tekton-operator
    reference-only: "true"
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
spec:
  channel: latest
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  startingCSV: openshift-pipelines-operator-rh.v1.18.1
status:
  # Current status from the live cluster
  currentCSV: openshift-pipelines-operator-rh.v1.18.1
  installedCSV: openshift-pipelines-operator-rh.v1.18.1
  state: AtLatestKnown
