FROM registry.access.redhat.com/ubi9/python-311:latest

RUN pip install mcp["cli"] httpx

WORKDIR /mcp_server

COPY submodule/mcp/ansible.py ansible.py

EXPOSE 8000

ENTRYPOINT [ "python", "ansible.py" ]
