apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: workshop-monitoring-service-image
  labels:
    app: workshop-monitoring-service
    component: monitoring
    part-of: workshop-template-system
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    annotations:
      description: The latest workshop monitoring service image
      iconClass: icon-java
      tags: monitoring,workshop,quarkus,java
    from:
      kind: DockerImage
      name: workshop-monitoring-service:latest
    importPolicy: {}
    referencePolicy:
      type: Local
