apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: workshop-monitoring-service-base

resources:
- deployment.yaml
- service.yaml
- route.yaml
- configmap.yaml
- buildconfig.yaml
- imagestream.yaml

labels:
- pairs:
    app.kubernetes.io/name: workshop-monitoring-service
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: workshop-template-system
    app.kubernetes.io/version: "1.0.0"

images:
- name: workshop-monitoring-service
  newTag: latest
