apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: agent-task-content-creator
  namespace: workshop-system
  labels:
    app: workshop-template-system
    component: content-creator-agent
    version: v1.0.0
spec:
  description: |
    Content Creator Agent Task
    Calls the Content Creator Agent via HTTP to create or enhance workshop content.
    Supports both new workshop creation (Workflow 1) and existing workshop enhancement (Workflow 3).
  
  params:
  - name: repository-url
    type: string
    description: Source repository URL for content creation
  - name: workshop-name
    type: string
    description: Name for the workshop
  - name: base-template
    type: string
    description: Base template to use (showroom_template_default or original_repository)
    default: "showroom_template_default"
  - name: analysis-result
    type: string
    description: Repository analysis result from Template Converter Agent
    default: ""
  - name: enhancement-plan
    type: string
    description: Enhancement plan for existing workshops (Workflow 3)
    default: ""
  - name: original-content
    type: string
    description: Original workshop content for enhancement (Workflow 3)
    default: ""
  - name: middleware-endpoint
    type: string
    description: Workshop Monitoring Service (Middleware) endpoint
    default: "http://workshop-monitoring-service:8080"
  - name: timeout-seconds
    type: string
    description: Timeout for agent call in seconds
    default: "600"
  - name: workspace-mode
    type: string
    description: Operation mode (hybrid, file-based, api-only)
    default: "hybrid"

  workspaces:
  - name: shared-data
    description: Shared workspace for workshop content
    optional: true

  results:
  - name: workshop-content
    description: Generated or enhanced workshop content
  - name: content-summary
    description: Summary of content creation or enhancement
  - name: enhanced-content
    description: Enhanced workshop content (for Workflow 3)
  - name: enhancement-summary
    description: Summary of enhancements applied (for Workflow 3)

  steps:
  - name: call-content-creator-agent
    image: registry.access.redhat.com/ubi8/ubi:latest
    script: |
      #!/bin/bash
      set -e

      echo "🎨 Content Creator Agent Task"
      echo "============================="
      echo "Repository URL: $(params.repository-url)"
      echo "Workshop Name: $(params.workshop-name)"
      echo "Base Template: $(params.base-template)"
      echo ""

      # Install required tools
      dnf install -y curl jq

      # Check if workspace is available (ADR-0007)
      if [ -d "/workspace/shared-data" ]; then
        echo "📁 Workspace available, using file-based operations"
        WORKSPACE_PATH="/workspace/shared-data"
        OPERATION_MODE="file-based"
        echo "Workspace Mode: $(params.workspace-mode)"
        echo "Workspace Path: $WORKSPACE_PATH"

        # Display workspace content
        echo ""
        echo "📂 Workspace Content:"
        ls -la /workspace/shared-data/ || echo "Workspace empty"
        if [ -d "/workspace/shared-data/workshop-content" ]; then
          echo ""
          echo "📁 Workshop Content:"
          ls -la /workspace/shared-data/workshop-content/ | head -10
        fi
        echo ""
      else
        echo "🌐 No workspace available, using API-only operations"
        WORKSPACE_PATH=""
        OPERATION_MODE="api-only"
      fi

      # Determine operation type based on parameters
      if [ -n "$(params.enhancement-plan)" ] && [ -n "$(params.original-content)" ]; then
        echo "📝 Operation: Workshop Enhancement (Workflow 3)"
        OPERATION_TYPE="ENHANCEMENT"
      else
        echo "🆕 Operation: New Workshop Creation (Workflow 1)"
        OPERATION_TYPE="CREATION"
      fi
      
      if [ "$OPERATION_TYPE" = "ENHANCEMENT" ]; then
        echo "🔄 Calling Content Creator Agent for Workshop Enhancement..."
        
        # Prepare enhancement request payload for middleware
        REQUEST_PAYLOAD=$(cat <<EOF
{
  "workshop_name": "$(params.workshop-name)",
  "repository_url": "$(params.repository-url)",
  "enhancement_plan": "$(params.enhancement-plan)",
  "original_content": "$(params.original-content)",
  "enhancement_type": "content-update"
}
EOF
        )

        # Call middleware endpoint
        RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" -X POST "$(params.middleware-endpoint)/api/pipeline/content-creator/enhance-workshop" \
          -H "Content-Type: application/json" \
          -d "$REQUEST_PAYLOAD" \
          --connect-timeout 30 \
          --max-time $(params.timeout-seconds))
        
      else
        echo "🆕 Calling Content Creator Agent for New Workshop Creation..."

        # Choose appropriate tool based on workspace availability
        if [ "$OPERATION_MODE" = "file-based" ]; then
          echo "📁 Using workspace-based content creation (Enhanced Workspace Demo)"

          # Since agent tools are not yet implemented, demonstrate workspace functionality
          echo "🎯 Demonstrating Enhanced Workspace Strategy (ADR-0007)"
          echo "Creating workshop content directly in shared workspace..."

          # Create content in the shared workspace
          PIPELINE_ID=$(basename "$(dirname "$WORKSPACE_PATH")")
          CONTENT_DIR="$WORKSPACE_PATH/final-output"
          mkdir -p "$CONTENT_DIR"

          # Create demo workshop content
          cat > "$CONTENT_DIR/workshop-info.json" <<EOF
{
  "workshop_name": "$(params.workshop-name)",
  "repository_url": "$(params.repository-url)",
  "base_template": "$(params.base-template)",
  "created_by": "enhanced-workspace-strategy",
  "adr": "0007",
  "creation_time": "$(date -Iseconds)",
  "workspace_path": "$WORKSPACE_PATH",
  "pipeline_id": "$PIPELINE_ID"
}
EOF

          # Create demo content structure
          mkdir -p "$CONTENT_DIR"/{content,exercises,resources}
          echo "# $(params.workshop-name)" > "$CONTENT_DIR/README.md"
          echo "Workshop created using Enhanced Workspace Strategy (ADR-0007)" >> "$CONTENT_DIR/README.md"
          echo "Repository: $(params.repository-url)" >> "$CONTENT_DIR/README.md"
          echo "Created: $(date)" >> "$CONTENT_DIR/README.md"

          # Simulate successful agent response
          AGENT_RESPONSE='{"status": "success", "message": "Workshop content created in shared workspace", "workspace_demo": true}'
          HTTP_STATUS=200
        else
          echo "🌐 Using middleware for workshop creation"

          # Prepare workshop creation request payload for middleware
          REQUEST_PAYLOAD=$(cat <<EOF
{
  "workshop_name": "$(params.workshop-name)",
  "repository_url": "$(params.repository-url)",
  "base_template": "$(params.base-template)",
  "target_directory": "/workspace/shared-data/final-output",
  "technology_focus": "$(params.repository-url)",
  "customization_level": "comprehensive"
}
EOF
          )
        fi

        echo "📝 Request Payload:"
        echo "$REQUEST_PAYLOAD" | jq .
        echo ""

        # Call middleware endpoint
        RESPONSE=$(curl -s -w "HTTPSTATUS:%{http_code}" -X POST "$(params.middleware-endpoint)/api/pipeline/content-creator/create-workshop" \
          -H "Content-Type: application/json" \
          -d "$REQUEST_PAYLOAD" \
          --connect-timeout 30 \
          --max-time $(params.timeout-seconds))
      fi
      
      # Extract HTTP status and body
      HTTP_STATUS=$(echo "$RESPONSE" | grep -o "HTTPSTATUS:[0-9]*" | cut -d: -f2)
      RESPONSE_BODY=$(echo "$RESPONSE" | sed -E 's/HTTPSTATUS:[0-9]*$//')
      
      echo "📊 Agent Response (HTTP $HTTP_STATUS):"
      echo "$RESPONSE_BODY" | jq . || echo "$RESPONSE_BODY"
      echo ""
      
      # Check HTTP status
      if [ "$HTTP_STATUS" != "200" ]; then
        echo "❌ Middleware call failed with HTTP status: $HTTP_STATUS"
        echo "Response: $RESPONSE_BODY"
        exit 1
      fi

      # Check for JSON error in response
      if echo "$RESPONSE_BODY" | jq -e '.error' > /dev/null 2>&1; then
        echo "❌ Middleware returned error:"
        echo "$RESPONSE_BODY" | jq -r '.error'
        exit 1
      fi
      
      # Extract and save results based on operation type
      if [ "$OPERATION_TYPE" = "ENHANCEMENT" ]; then
        # Enhancement operation results
        if echo "$RESPONSE_BODY" | jq -e '.enhanced_content' > /dev/null 2>&1; then
          ENHANCED_CONTENT=$(echo "$RESPONSE_BODY" | jq -r '.enhanced_content')
          echo "$ENHANCED_CONTENT" > $(results.enhanced-content.path)
          echo "$ENHANCED_CONTENT" > $(results.workshop-content.path)  # Also set main result
          
          ENHANCEMENT_SUMMARY=$(echo "$RESPONSE_BODY" | jq -r '.enhancement_summary // "Workshop content enhanced successfully"')
          echo "$ENHANCEMENT_SUMMARY" > $(results.enhancement-summary.path)
          echo "$ENHANCEMENT_SUMMARY" > $(results.content-summary.path)  # Also set main summary
          
          echo "✅ Workshop enhancement completed successfully"
        else
          echo "❌ Invalid enhancement response - missing 'enhanced_content' field"
          exit 1
        fi
      else
        # Creation operation results
        if echo "$RESPONSE_BODY" | jq -e '.workshop_content' > /dev/null 2>&1; then
          WORKSHOP_CONTENT=$(echo "$RESPONSE_BODY" | jq -r '.workshop_content')
          echo "$WORKSHOP_CONTENT" > $(results.workshop-content.path)
          
          CONTENT_SUMMARY=$(echo "$RESPONSE_BODY" | jq -r '.content_summary // "Workshop content created successfully"')
          echo "$CONTENT_SUMMARY" > $(results.content-summary.path)
          
          echo "✅ Workshop creation completed successfully"
        else
          echo "❌ Invalid creation response - missing 'workshop_content' field"
          exit 1
        fi
      fi

  - name: log-content-summary
    image: registry.access.redhat.com/ubi8/ubi:latest
    script: |
      #!/bin/bash
      
      OPERATION_TYPE=$(cat /tmp/operation-type)
      
      echo "📋 Content Creator Agent Summary"
      echo "==============================="
      echo "Repository URL: $(params.repository-url)"
      echo "Workshop Name: $(params.workshop-name)"
      echo "Operation Type: $OPERATION_TYPE"
      echo ""
      
      if [ "$OPERATION_TYPE" = "ENHANCEMENT" ]; then
        echo "🔄 Workshop Enhancement Results:"
        echo "  Enhancement Plan Applied: $(params.enhancement-plan)"
        if [ -f "$(results.enhancement-summary.path)" ]; then
          echo "  Enhancement Summary: $(cat $(results.enhancement-summary.path))"
        fi
      else
        echo "🆕 New Workshop Creation Results:"
        echo "  Base Template: $(params.base-template)"
        if [ -f "$(results.content-summary.path)" ]; then
          echo "  Content Summary: $(cat $(results.content-summary.path))"
        fi
      fi
      
      if [ -f "$(results.workshop-content.path)" ]; then
        CONTENT_LENGTH=$(cat $(results.workshop-content.path) | wc -c)
        echo "  Content Length: $CONTENT_LENGTH characters"
      fi
      
      echo ""
      echo "🚀 Workshop content ready for next pipeline stage"
